#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-booleanoperations
Version  : 0.9.0
Release  : 13
URL      : https://files.pythonhosted.org/packages/57/d9/9eae7bc4ba3a38ab7426522fb08e12df54aec27595d7bcd1bc0670aec873/booleanOperations-0.9.0.zip
Source0  : https://files.pythonhosted.org/packages/57/d9/9eae7bc4ba3a38ab7426522fb08e12df54aec27595d7bcd1bc0670aec873/booleanOperations-0.9.0.zip
Summary  : Boolean operations on paths.
Group    : Development/Tools
License  : MIT
Requires: pypi-booleanoperations-license = %{version}-%{release}
Requires: pypi-booleanoperations-python = %{version}-%{release}
Requires: pypi-booleanoperations-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(fonttools)
BuildRequires : pypi(py)
BuildRequires : pypi(pyclipper)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
BooleanOperations
        =================
        
        Boolean operations on paths which uses a super fast `polygon clipper

%package license
Summary: license components for the pypi-booleanoperations package.
Group: Default

%description license
license components for the pypi-booleanoperations package.


%package python
Summary: python components for the pypi-booleanoperations package.
Group: Default
Requires: pypi-booleanoperations-python3 = %{version}-%{release}

%description python
python components for the pypi-booleanoperations package.


%package python3
Summary: python3 components for the pypi-booleanoperations package.
Group: Default
Requires: python3-core
Provides: pypi(booleanoperations)
Requires: pypi(fonttools)
Requires: pypi(pyclipper)

%description python3
python3 components for the pypi-booleanoperations package.


%prep
%setup -q -n booleanOperations-0.9.0
cd %{_builddir}/booleanOperations-0.9.0
pushd ..
cp -a booleanOperations-0.9.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656362015
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-booleanoperations
cp %{_builddir}/booleanOperations-0.9.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-booleanoperations/3bdf95815fd839c7dc1d192732ac14bb012d9eef
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-booleanoperations/3bdf95815fd839c7dc1d192732ac14bb012d9eef

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
